# enable/disable checking for application updates on startup
check-for-app-update: false

# same as -o ; the output format of the vulnerability report (options: table, json, cyclonedx)
output: "table"

quiet: false

# same as --file; write output report to a file (default is to write to stdout)
file: "grype-yaml.out"
