name: "Docker scan with Anchore"

on:
  push:
    branches: [main]

jobs:
  scan-vex:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: anchore/scan-action@dependabot/npm_and_yarn/actions/core-3.0.0
        id: scan
        with:
          image: alpine:3.15
          output-format: sarif
          output-file: scan.grype.json
          fail-build: false

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
          
      - run: |
          cat scan.grype.json

      - uses: actions/upload-artifact@v5
        with:
          name: scan-report
          path: scan.grype.json
