name: "Run Scan Action"

on:
  workflow_dispatch:
  push:


jobs:
  sarif-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: yarn

    - run: |
        set -x
        ls -alFh .
        cat .grype.yaml
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b ./grype
        grype/grype --help
        grype -vv dir:. -o json --file grype.out
        ls -alFh .


    - name: Run the latest released Scan Action with SARIF generation enabled
      uses: kzantow-anchore/scan-action@fix/read-grype-yaml
      with:
        path: "."
        debug: true
        fail-build: false

    - run: ls -alFh .

#    - uses: actions/upload-artifact@v2
#      with:
#        name: files
#        path: |
#          vulnerabilities.json
#          results.sarif
#
#    - run: cat results.sarif
#
#    - uses: github/codeql-action/upload-sarif@v1
#      with:
#        sarif_file: results.sarif

#  codeql:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v1
#        with:
#          languages: javascript
#
#      - run: yarn
#
#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v1
