name: "Run Scan Action"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sarif-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run the latest released Scan Action with SARIF generation enabled
      uses: anchore/scan-action@next
      with:
        path: "."
        debug: true
        fail-build: false
        acs-report-enable: true

    - uses: actions/upload-artifacts@v2
      with:
        name: files
        path: |
          vulnerabilities.json
          results.sarif

    - run: cat results.sarif

    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
