name: "Run Scan Action"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: anchore/sbom-action@v3
        with:
          image: "alpine:3.16"
          format: json
          output-file: sbom.json

      - name: Run the Anchore scan action
        uses: anchore/scan-action@v0
        id: scan
        with:
          sbom: sbom.json
          fail-build: true
          severity-cutoff: critical
          output-format: table

      - name: Upload Anchore scan Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
