name: "Run Scan Action"

on:
  workflow_dispatch:
  push:


jobs:
  sarif-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: "^1.17.6"

    - run: |
        set -xe
        curl -L -o sarif-presenter.zip https://github.com/kzantow-anchore/grype/archive/refs/heads/sarif-presenter.zip
        unzip sarif-presenter.zip
        cd grype-sarif-presenter
        go run main.go alpine:3.10 -o sarif --file ../results.sarif
        ls -alFh .
        cat results.sarif

    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

#  codeql:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v1
#        with:
#          languages: javascript
#
#      - run: yarn
#
#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v1
