name: "Run Scan Action"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anchore/sbom-action@9fece9e20048ca9590af301449208b2b8861333b
        with:
          image: "alpine:3.15"
          format: json
          output-file: sbom.json
      - name: Run the Anchore scan action
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a
        id: scan
        with:
#          image: "alpine:3.15"
          sbom: sbom.json
          fail-build: true
          severity-cutoff: critical
          output-format: table
#      - name: Upload Anchore scan Report
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: ${{ steps.scan.outputs.sarif }}
