name: "Docker scan with Anchore"

on:
  push:
    branches: [main]

jobs:
  scan-vex:
    name: Scan image with VEX file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Scan Docker image with Grype'
        uses: anchore/scan-action@latest
        with:
          image: alpine:3.15
          output-format: json
          output-file: scan.grype.json
          registry-username: FOOBAR_USER
          registry-password: FOOBAR_PASS

      - name: Print result file
        if: always()
        run: |
          echo "Content of Grype output file file:"
          cat scan.grype.json
